language: scala
scala: 2.12.1

dist: trusty
sudo: required
jdk: oraclejdk8

before_install:
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.2.0-rc0.tar.gz
  - tar xvf libtensorflow-cpu-linux-x86_64-1.2.0-rc0.tar.gz
  - export LD_LIBRARY_PATH=LD_LIBRARY_PATH:`pwd`/libtensorflow-cpu-linux-x86_64-1.2.0-rc0/lib/libtensorflow.so
