language: scala
scala:
  - 2.12.1

os: osx
osx_image: xcode8

before_install:
  - wget https://www.dropbox.com/s/zedd75zvay31x6o/libtensorflow.so
  - sudo cp libtensorflow.so /usr/lib/libtensorflow.so
