language: scala
scala: 2.12.1

dist: trusty
sudo: required
jdk: oraclejdk8

include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env: CXX=g++-4.9

before_install:
  - export PATH=${PATH}:./vendor/bundle
  - wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
  - sudo unzip protoc-3.3.0-linux-x86_64.zip -d /usr
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.3.0-rc0.tar.gz
  - sudo tar xvf libtensorflow-cpu-linux-x86_64-1.3.0-rc0.tar.gz -C /usr

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt compile
