language: scala
scala: 2.12.1

dist: trusty
sudo: required
jdk: oraclejdk8

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

before_install:
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.2.0-rc0.tar.gz
  - tar xvf libtensorflow-cpu-linux-x86_64-1.2.0-rc0.tar.gz
  - sudo cp lib/libtensorflow.so /usr/lib/libtensorflow.so
